"""
Initial migration
"""
revision = '0001'
down_revision = None
from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marcas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre')
    )
    op.create_table('modelos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(), nullable=False),
        sa.Column('marca_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estados',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre')
    )
    op.create_table('autos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('marca_id', sa.Integer(), nullable=True),
        sa.Column('modelo_id', sa.Integer(), nullable=True),
        sa.Column('anio', sa.Integer(), nullable=True),
        sa.Column('tipo', sa.String(), nullable=True),
        sa.Column('precio', sa.Float(), nullable=True),
        sa.Column('descripcion', sa.String(), nullable=True),
        sa.Column('en_stock', sa.Boolean(), nullable=True),
        sa.Column('estado_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['marca_id'], ['marcas.id'], ),
        sa.ForeignKeyConstraint(['modelo_id'], ['modelos.id'], ),
        sa.ForeignKeyConstraint(['estado_id'], ['estados.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagenes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('auto_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizaciones',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_usuario', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('telefono', sa.String(), nullable=True),
        sa.Column('auto_id', sa.Integer(), nullable=True),
        sa.Column('mensaje', sa.String(), nullable=True),
        sa.Column('estado', sa.String(), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presupuestos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('auto_id', sa.Integer(), nullable=True),
        sa.Column('precio_sugerido', sa.Float(), nullable=True),
        sa.Column('comentarios', sa.String(), nullable=True),
        sa.Column('estado', sa.String(), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes_venta',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre_interesado', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('telefono', sa.String(), nullable=True),
        sa.Column('auto_id', sa.Integer(), nullable=True),
        sa.Column('mensaje', sa.String(), nullable=True),
        sa.Column('estado', sa.String(), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    op.drop_table('solicitudes_venta')
    op.drop_table('presupuestos')
    op.drop_table('cotizaciones')
    op.drop_table('imagenes')
    op.drop_table('autos')
    op.drop_table('estados')
    op.drop_table('modelos')
    op.drop_table('marcas')
    # ### end Alembic commands ###
