# Alembic migration script
"""
Revision ID: 55e169a86147
Revises: 0001
Create Date: 2026-01-25 15:09:09.684673
"""
revision = '55e169a86147'
down_revision = '0001'
from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_cloudinary',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cloud_name', sa.String(), nullable=False),
        sa.Column('api_key', sa.String(), nullable=False),
        sa.Column('api_secret', sa.String(), nullable=False),
        sa.Column('upload_preset', sa.String(), nullable=False),
        sa.Column('activo', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracion_cloudinary')
    # ### end Alembic commands ###
