# Alembic migration script
"""
Revision ID: b0f67e94d3d6
Revises: f3af752d39a3
Create Date: 2026-02-06 23:48:57.343408
"""
from alembic import op
import sqlalchemy as sa

revision = 'b0f67e94d3d6'
down_revision = 'f3af752d39a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotizaciones', sa.Column('ciudad', sa.String(), nullable=True))
    op.add_column('cotizaciones', sa.Column('fuente', sa.String(), nullable=True))
    op.add_column('cotizaciones', sa.Column('preferencias_contacto', sa.String(), nullable=True))
    op.add_column('cotizaciones', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('cotizaciones', sa.Column('estado_oportunidad', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotizaciones', 'estado_oportunidad')
    op.drop_column('cotizaciones', 'score')
    op.drop_column('cotizaciones', 'preferencias_contacto')
    op.drop_column('cotizaciones', 'fuente')
    op.drop_column('cotizaciones', 'ciudad')
    # ### end Alembic commands ###
