"""add_clientes_and_oportunidades_tables

Revision ID: bd97f14bb50c
Revises: 9f4c61b97935
Create Date: 2026-02-08 12:00:29.720890
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bd97f14bb50c'
down_revision = '9f4c61b97935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('fuente', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('preferencias_contacto', sa.String(), nullable=True),
    sa.Column('presupuesto_min', sa.Integer(), nullable=True),
    sa.Column('presupuesto_max', sa.Integer(), nullable=True),
    sa.Column('tipo_vehiculo_interes', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('ultimo_contacto', sa.DateTime(), nullable=True),
    sa.Column('ip_registro', sa.String(), nullable=True),
    sa.Column('ubicacion_geo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_email'), 'clientes', ['email'], unique=True)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('oportunidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('auto_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('etapa', sa.String(), nullable=True),
    sa.Column('probabilidad', sa.Integer(), nullable=True),
    sa.Column('valor_estimado', sa.Float(), nullable=True),
    sa.Column('prioridad', sa.String(), nullable=True),
    sa.Column('motivo_perdida', sa.String(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('proxima_accion', sa.String(), nullable=True),
    sa.Column('fecha_proxima_accion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auto_id'], ['autos.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oportunidades_id'), 'oportunidades', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oportunidades_id'), table_name='oportunidades')
    op.drop_table('oportunidades')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_email'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
