# Alembic migration script
"""
Revision ID: f3af752d39a3
Revises: 20d76f134020
Create Date: 2026-01-27 11:16:45.754677
"""
from alembic import op
import sqlalchemy as sa

revision = 'f3af752d39a3'
down_revision = '20d76f134020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagenes', sa.Column('titulo', sa.String(), nullable=True))
    op.add_column('imagenes', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('imagenes', sa.Column('alt', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imagenes', 'alt')
    op.drop_column('imagenes', 'descripcion')
    op.drop_column('imagenes', 'titulo')
    # ### end Alembic commands ###
